### ISSUE TITLE
[Client] Header 생성

### ISSUE THREAD

**Issue by TTurbo0824** [TTurbo0824/WalkingDog#10]
### ISSUE
* Group: `client`
* Type: `feature`
* Detail: create header
### TODO
- [x] Header 위치 잡기
- [x] Header 상단 고정
- [x] Detail 항목 생성 및 라우팅
### Labels
* Estimated time: `E: 1h`
* Group : `client`
* Urgency: `Low`
