### ISSUE TITLE
[Client] Login Modal 생성 및 기능 구현

### ISSUE THREAD

**Issue by TTurbo0824** [TTurbo0824/WalkingDog#11]
### ISSUE
* Group: `client`
* Type: `feature`
* Detail: create login modal
### TODO
- [x] 로그인 모달 생성
- [x] 로그인 모달 서버 연결
- [x] 게스트 처험 기능 추가
### Labels
* Estimated time: `E: 2.5h`
* Group : `client`
* Urgency: `High`
