### ISSUE TITLE
[Server / Client] My Info Page: 프로필 사진 설정 기능

### ISSUE THREAD

**Issue by TTurbo0824** [TTurbo0824/WalkingDog#114]
### ISSUE
* Group: `server`, `client`
* Type: `feature`
* Detail: create a feature for setting a profile photo
### TODO
- [x] 프로필 사진 설정 기능 구현
- [x] 프로필 사진 설정 Redux action 추가
- [x] 이미지 미리보기 기능 구현
- [x] 프로필 사진 설정 컨트롤러 구현
- [x] 프로필 사진 용량/파일 확장자 제한
### Labels
* Estimated time: `E: 3h`
* Group : `client`
* Urgency: `High`
