### ISSUE TITLE
[Client] My Page: 반응형 적용 & CSS 개선

### ISSUE THREAD

**Issue by TTurbo0824** [TTurbo0824/WalkingDog#124]
### ISSUE
* Group: `client`
* Type: `css`
* Detail: improve my page css
### TODO
- [x] 마이 페이지 CSS 개선
- [x] 내 정보 페이지 반응형 적용
- [x] 요청 내역 페이지 반응형 적용
- [x] 이용 내역 페이지 반응형 적용
- [x] 평점 모달 반응형 적용
- [x] 리뷰 모달 반응형 적용
### Labels
* Estimated time: `E: 3h`
* Group : `client`
* Urgency: `Medium`
