### ISSUE TITLE
[Client] Dog Walker Detail Page: Basic Content 틀 잡기

### ISSUE THREAD

**Issue by TTurbo0824** [TTurbo0824/WalkingDog#26]
### ISSUE
* Group: `client`
* Type: `feature`
* Detail: create a basic content layout on the dog walker detail page
### TODO
- [x] 도그워커 세부 정보 항목 생성 (기본 정보, 가격, 태그)
- [x] 도그워커 요금 정보 표기
- [x] 요청 컨테이너 생성 (장소, 견종, 날짜, 시간 등 정보 포함)
### Labels
* Estimated time: `E: 3h`
* Group : `client`
* Urgency: `High`
