### ISSUE TITLE
[Server] Requests Controllers 생성 및 기능 구현

### ISSUE THREAD

**Issue by TTurbo0824** [TTurbo0824/WalkingDog#6]
### ISSUE
* Group: `server`
* Type: `feature`
* Detail: create requests controllers
### TODO
- [x] 요청 조회 컨트롤러 생성 및 기능 구현
- [x] 요청 보내기 컨트롤러 생성 및 기능 구현
- [x] 요청 취소 컨트롤러 생성 및 기능 구현
### Labels
* Estimated time: `E: 3h`
* Group : `server`
* Urgency: `High`
